
import java.util.Scanner;
// package - a namespace that organizes a set of related classes and interfaces
// basic structure of a Java program consists of classes, methods, and statements
// a Java program is executed by the Java Virtual Machine (JVM), which interprets the bytecode generated by the Java compiler

class InputOutput {
// public - class can be accessed from anywhere
// class- named group of objects with similar properties and methods
// main.java - public class name should match the file name
// main - entry point of the program
//static- method belongs to the class rather than an instance of the class
//void-method does not return any value
//String[] args- command line arguments passed to the program

    static class Solver {
        public void printNumber(Scanner sc) {
            
            System.out.print("Enter a number: ");
            int num = sc.nextInt();
            System.out.println("You entered: " + num);
        }
    }

    public static void main(String... args) {
        Scanner sc = new Scanner(System.in);
        Solver solver = new Solver();
        solver.printNumber(sc);
        // objects are instances of classes that can hold data and have methods to perform actions
        // Scanner is a class in java.util package that is used to read input from various sources, including user input from the console
        // objects are created using the new keyword, which allocates memory for the object and calls its constructor
        // objects are used to access the methods and properties of the class they belong to
        // we cannot code outside of a class in Java, as all code must be contained within a class definition
        // string , int , double, boolean, char, float, long, short, byte are primitive data types in Java that represent simple values-
        // they cannot be breaken into smaller parts or objects
        // literals are fixed values that are directly written in the code, such as numbers, characters, or strings
        //identifiers are names given to variables, methods, classes, and other elements in Java to uniquely identify them
        // typecasting is the process of converting a value from one data type to another, either implicitly or explicitly
        // typecasting is posssible between compatible data types, such as int to double or char to int, but may result in loss of precision or data if not done carefully
        sc.close();
    }
}